/* Apartmani Elegance — shared navbar + footer component injector.
 * Placed as a synchronous (no defer/async) script before webflow.js so
 * Webflow's DOMContentLoaded handler sees the injected elements.
 * Uses root-relative paths so the same HTML works from / and /blog/. */
(function () {
  var NAVBAR = [
    '<div data-animation="over-left" class="navbar second w-nav" data-easing2="ease" data-easing="ease"',
    '  data-collapse="medium" data-w-id="39b51dbc-db1a-3469-2649-4f86d199ac94" role="banner"',
    '  data-duration="350" data-doc-height="1">',
    '  <div class="navbar-container w-container">',
    '    <div class="brand-wrapper">',
    '      <a href="/index.html" class="brand w-nav-brand">',
    '        <img src="/images/elegance-logo-navbar.svg" loading="lazy" alt="Apartmani Elegance Tuzla logo" class="image-25">',
    '      </a>',
    '    </div>',
    '    <nav role="navigation" class="nav-menu w-nav-menu">',
    '      <a href="/index.html" class="navbar-link w-inline-block">',
    '        <div class="navbar-link-text">Naslovna</div>',
    '        <div class="navbar-underline"></div>',
    '      </a>',
    '      <a href="/index.html#ponuda-apartmana" class="navbar-link w-inline-block">',
    '        <div class="navbar-link-text">Ponuda</div>',
    '        <div class="navbar-underline"></div>',
    '      </a>',
    '      <a href="/index.html#recenzije" class="navbar-link w-inline-block">',
    '        <div class="navbar-link-text">Recenzije</div>',
    '        <div class="navbar-underline"></div>',
    '      </a>',
    '      <a href="/index.html#lokacija" class="navbar-link w-inline-block">',
    '        <div class="navbar-link-text">Lokacija</div>',
    '        <div class="navbar-underline"></div>',
    '      </a>',
    '      <a href="/blog/" class="navbar-link w-inline-block">',
    '        <div class="navbar-link-text">Blog</div>',
    '        <div class="navbar-underline"></div>',
    '      </a>',
    '    </nav>',
    '    <div class="nav-col3-wrapper">',
    '      <a href="/rezervacija.html" class="yellow-button navbar-yellow-button w-inline-block">',
    '        <div class="button-content">',
    '          <div class="button-text navbar-button-text">Rezervacija</div>',
    '        </div>',
    '      </a>',
    '      <a href="https://www.booking.com/hotel/ba/apartmani-tuzla-tuzla.hr.html" class="booking-link w-inline-block">',
    '        <img src="/images/booking-logo.svg" loading="lazy" width="48" height="48" alt="booking.com-logo" class="image">',
    '      </a>',
    '      <div data-w-id="39b51dbc-db1a-3469-2649-4f86d199acb4" class="menu-button w-nav-button">',
    '        <img src="/images/menu-elegance.svg" loading="lazy" alt="" class="menu">',
    '      </div>',
    '    </div>',
    '  </div>',
    '</div>'
  ].join('\n');

  var FOOTER = [
    '<section class="footer">',
    '  <div class="container-2">',
    '    <div class="footer-wrapper-two">',
    '      <div class="col1-footer-brand-wrapper">',
    '        <a href="/index.html" class="footer-brand w-inline-block">',
    '          <img src="/images/footer-logo.svg" loading="lazy" alt="Apartmani Elegance Tuzla">',
    '        </a>',
    '        <div class="footer-brand-text">Dobrodošli u Elegance apartmane. Počevši sa radom od 2018. godine, naša ponuda sastoji se od 4 savremeno opremljena apartmana.</div>',
    '      </div>',
    '      <div class="footer-block-two">',
    '        <div class="footer-title">Sekcije</div>',
    '        <a href="/index.html" class="footer-link-two">Naslovna</a>',
    '        <a href="/index.html#ponuda-apartmana" class="footer-link-two">Ponuda</a>',
    '        <a href="/index.html#recenzije" class="footer-link-two">Recenzije</a>',
    '        <a href="/index.html#lokacija" class="footer-link-two">Lokacija</a>',
    '        <a href="/index.html#pravilnik" class="footer-link-two">Pravilnik</a>',
    '      </div>',
    '      <div class="footer-block-two">',
    '        <div class="footer-title">Apartmani</div>',
    '        <a href="/deluxe-apartman.html" class="footer-link-two">Deluxe Apartman</a>',
    '        <a href="/trosoban-apartman.html" class="footer-link-two">Trosoban Apartman</a>',
    '        <a href="/dvosoban-apartman.html" class="footer-link-two">Dvosoban Apartman</a>',
    '        <a href="/dvosoban-apartman-sa-dnevnim-boravkom.html" class="footer-link-two">Dvosoban sa dnevnim boravkom</a>',
    '      </div>',
    '      <div class="footer-block-two">',
    '        <div class="footer-title">Vodiči i lokacije</div>',
    '        <a href="/apartmani-blizu-panonskih-jezera.html" class="footer-link-two">Apartmani blizu Panonskih jezera</a>',
    '        <a href="/blog/" class="footer-link-two">Blog</a>',
    '      </div>',
    '      <div class="footer-block-two">',
    '        <div class="footer-title">Kontakt informacije</div>',
    '        <a href="tel:+38761944061" class="footer-link-two">+387/61-944-061</a>',
    '        <a href="https://g.co/kgs/ap9i2xV" class="footer-link-two">Donji Mosnik 7, Tuzla 75000, Bosna i Hercegovina.</a>',
    '        <a href="mailto:apartmanielegance@gmail.com" class="footer-link-two">apartmanielegance@gmail.com</a>',
    '      </div>',
    '      <div class="footer-block-two">',
    '        <div class="footer-title">Posjetite nas na platformama</div>',
    '        <div class="link-blocks-footer-socials">',
    '          <a href="https://www.booking.com/hotel/ba/apartmani-tuzla-tuzla.hr.html" target="_blank" class="social-media-link w-inline-block">',
    '            <img src="/images/booking-circle-logo.svg" loading="lazy" alt="Apartmani Elegance na Booking.com">',
    '          </a>',
    '          <a href="https://airbnb.com/h/elegance-apartments-in-tuzla" target="_blank" class="social-media-link w-inline-block">',
    '            <img src="/images/airbnb-circle-logo.svg" loading="lazy" alt="Apartmani Elegance na Airbnb">',
    '          </a>',
    '          <a href="https://www.instagram.com/apartmani.elegance" target="_blank" class="social-media-link last-sml w-inline-block">',
    '            <img src="/images/ig-circle-logo.svg" loading="lazy" alt="Apartmani Elegance na Instagramu">',
    '          </a>',
    '        </div>',
    '      </div>',
    '    </div>',
    '    <div class="footer-divider-two"></div>',
    '    <div class="footer-bottom">',
    '      <a href="https://www.linkedin.com/in/eldardizdarevic/" target="_blank" class="eldars-social w-inline-block">',
    '        <div class="footer-copyright">© 2026 Apartmani Elegance x Eldar Dizdarević</div>',
    '      </a>',
    '    </div>',
    '  </div>',
    '</section>'
  ].join('\n');

  function inject(id, html) {
    var el = document.getElementById(id);
    if (el) el.outerHTML = html;
  }

  inject('ael-navbar', NAVBAR);
  inject('ael-footer', FOOTER);
})();
